version: '3.3'

services:

  db:
    image: postgres:alpine
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgresDB_data:/var/lib/postgresql/data
    
  auth:
    image: plotlinebilling/auth-service
    env_file:
      - ./.env
    environment:
      - PORT=4001
    ports:
      - "4001:4001"

  commerce:
    image: plotlinebilling/commerce-service
    env_file:
      - ./.env
    environment:
      - PORT=5001
    ports:
      - "5001:5001"

  orders-billings:
    image: plotlinebilling/orders-billings
    env_file:
      - ./.env
    environment:
      - PORT=6001
    ports:
      - "6001:6001"

volumes:
  postgresDB_data:
